In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("/Users/abhimanyu/Developer/Projects/Income_classifier/Data/income_data.csv")
df.head()

,Workclass,Education,Marital-Status,Occupation,Relationship,Race,Sex,Native_country,Target
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K

In [8]:
df.tail()

,Workclass,Education,Marital-Status,Occupation,Relationship,Race,Sex,Native_country,Target
30157,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
30158,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
30159,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
30160,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K
30161,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,>50K